language: node_js
node_js: 
  - "node"
install: npm install
services: 
    - postgresql
before_script:
   - npm install -g jasmine
  - psql -c 'create database test_db;' -U postgres
script: npm test
after_success: npm run coverage
cache:
  directories:
    - "node_modules"
