language: node_js
node_js: 
  - 12
install: npm install
services: 
    - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script: jasmine
after_success: npm run coverage
cache:
  directories:
    - "node_modules"
